contentType:
  - type: "f5fe4c5c-67db-465a-aba6-75618cdcbf30"
    name: [productCode,productTitle]
    fieldMapping:
      - csvProperty: productCode
        acousticProperty: productCode
        propertyType: number
      - csvProperty: productTitle
        acousticProperty: productTitle
        propertyType: text
      - csvProperty: productUrl
        acousticProperty: productUrl
        propertyType: link
      - csvProperty: productCategory
        acousticProperty: productCategory
        propertyType: category
        categoryName: "TRS Product Category"

