contentType:
  - type: "f5fe4c5c-67db-465a-aba6-75618cdcbf30"
    csvRecordKey : productCode
    name: [productCode,productTitle]
    tags: [moodboard,reece,test]
    fieldMapping:
      - csvProperty: productCode
        acousticProperty: productCode
        propertyType: number
      - csvProperty: Description
        acousticProperty: productTitle
        propertyType: text
      - csvProperty: Website Link
        acousticProperty: productUrl
        propertyType: link
      - csvProperty: Category
        acousticProperty: productCategory
        propertyType: category
        categoryName: "TRS Product Category"
      - csvProperty: Brand
        acousticProperty: productBrand
        propertyType: category
        categoryName: "TRS Brands"
      - csvProperty: colour
        acousticProperty: productColor
        propertyType: category
        categoryName: "TRS Product Color"
      - csvProperty: Image Name
        acousticProperty: productImage
        propertyType: image
        assetName:
        - refCSVProperty: productCode
          propertyName: productCode
        profiles: ["ae34cc92-8144-4d78-9660-c7d20abc0817"]
        assetLocation: "reece_images"
        acousticAssetBasePath: "/dxdam/moodboard/reece"
category:
  - parent: "TRS Brands"
    column: "Brand"
delete:
  - name: "Delete Reece Moodboard content"
    assetType: document
    search:
      contentType: "Moodboard Reece Product"
      classification: content
      searchTerm: "tags:reece AND tags:moodboard AND tags:test"
  - name: "Delete Reece Moodboard images"
    assetType: image
    search:
      classification: asset
      searchTerm: "tags:reece AND tags:moodboard AND tags:test"




